# https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/test.yml

name: ci

on:
  pull_request:
    paths-ignore:
    - 'README.md'
  push:
    paths-ignore:
    - 'README.md'

  schedule:
  - cron: '0 13 * * *'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

    - uses: actions/setup-go@v1
      with:
        go-version: '1.16'

    - name: test and build
      env:
        VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        make
        